"""empty message

Revision ID: c40f3a10f4e9
Revises: d6cbb59475df
Create Date: 2023-02-01 23:20:25.890404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40f3a10f4e9'
down_revision = 'd6cbb59475df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.alter_column('solicitud',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('impuestos', schema=None) as batch_op:
        batch_op.alter_column('solicitud',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impuestos', schema=None) as batch_op:
        batch_op.alter_column('solicitud',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('balance', schema=None) as batch_op:
        batch_op.alter_column('solicitud',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
