"""empty message

Revision ID: d6cbb59475df
Revises: 86aa52ed3450
Create Date: 2023-02-01 23:01:09.413547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6cbb59475df'
down_revision = '86aa52ed3450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.alter_column('solicitud',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingresos', schema=None) as batch_op:
        batch_op.alter_column('solicitud',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
